export const updateUserAddress = "UPDATE_USER_ADDRESS"
export const updateUserBalance = "UPDATE_USER_BALANCE"
export const updateUserProvider = "UPDATE_USER_PROVIDER"
export const updateUserChainId = "UPDATE_USER_CHAIN_ID"
export const updateUserSigner = "UPDATE_USER_SIGNER"
export const updateUserTheme = "UPDATE_USER_THEME"
